server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  ocr:
    tesseract:
      path: /usr/share/tesseract-ocr/4.00/tessdata/